packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  fortawesome/fontawesome-svg-core: 6.6.0
  fortawesome/free-solid-svg-icons: 6.6.0
  fortawesome/react-fontawesome: 0.2.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
